package com.lisz.flyweight;

public class Main {
	public static void main(String[] args) {
		Bullet.removeABullet();
		for (int i = 0; i < 11; i++) {
			Bullet bullet = Bullet.getInstance();
		}
	}
	/*  只new了10次，有一次是从pool里拿的
	 *  Creating a new bullet...
	    Creating a new bullet...
		Creating a new bullet...
		Creating a new bullet...
		Creating a new bullet...
		Creating a new bullet...
		Creating a new bullet...
		Creating a new bullet...
		Creating a new bullet...
		Creating a new bullet...
	 */
}
